// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: vies.proto

package vies

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VATValidationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CountryCode string                                    `protobuf:"bytes,1,opt,name=CountryCode,proto3" json:"CountryCode,omitempty"`
	VATNumber   string                                    `protobuf:"bytes,2,opt,name=VATNumber,proto3" json:"VATNumber,omitempty"`
	RequestDate *timestamppb.Timestamp                    `protobuf:"bytes,3,opt,name=RequestDate,proto3" json:"RequestDate,omitempty"`
	Valid       bool                                      `protobuf:"varint,4,opt,name=Valid,proto3" json:"Valid,omitempty"`
	Name        string                                    `protobuf:"bytes,5,opt,name=Name,proto3" json:"Name,omitempty"`
	Address     string                                    `protobuf:"bytes,6,opt,name=Address,proto3" json:"Address,omitempty"`
	Error       *VATValidationResponse_VATValidationError `protobuf:"bytes,7,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *VATValidationResponse) Reset() {
	*x = VATValidationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vies_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VATValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VATValidationResponse) ProtoMessage() {}

func (x *VATValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vies_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VATValidationResponse.ProtoReflect.Descriptor instead.
func (*VATValidationResponse) Descriptor() ([]byte, []int) {
	return file_vies_proto_rawDescGZIP(), []int{0}
}

func (x *VATValidationResponse) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *VATValidationResponse) GetVATNumber() string {
	if x != nil {
		return x.VATNumber
	}
	return ""
}

func (x *VATValidationResponse) GetRequestDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestDate
	}
	return nil
}

func (x *VATValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VATValidationResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VATValidationResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VATValidationResponse) GetError() *VATValidationResponse_VATValidationError {
	if x != nil {
		return x.Error
	}
	return nil
}

type VATValidationResponse_VATValidationError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FaultCode   string `protobuf:"bytes,1,opt,name=FaultCode,proto3" json:"FaultCode,omitempty"`
	FaultString string `protobuf:"bytes,2,opt,name=FaultString,proto3" json:"FaultString,omitempty"`
}

func (x *VATValidationResponse_VATValidationError) Reset() {
	*x = VATValidationResponse_VATValidationError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vies_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VATValidationResponse_VATValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VATValidationResponse_VATValidationError) ProtoMessage() {}

func (x *VATValidationResponse_VATValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_vies_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VATValidationResponse_VATValidationError.ProtoReflect.Descriptor instead.
func (*VATValidationResponse_VATValidationError) Descriptor() ([]byte, []int) {
	return file_vies_proto_rawDescGZIP(), []int{0, 0}
}

func (x *VATValidationResponse_VATValidationError) GetFaultCode() string {
	if x != nil {
		return x.FaultCode
	}
	return ""
}

func (x *VATValidationResponse_VATValidationError) GetFaultString() string {
	if x != nil {
		return x.FaultString
	}
	return ""
}

var File_vies_proto protoreflect.FileDescriptor

var file_vies_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x76, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x76, 0x69,
	0x65, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xf5, 0x02, 0x0a, 0x15, 0x56, 0x41, 0x54, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x56, 0x41, 0x54, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x56, 0x41, 0x54, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x3c, 0x0a,
	0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x44, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x76, 0x69, 0x65, 0x73, 0x2e, 0x56, 0x41, 0x54, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x41, 0x54, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x54, 0x0a, 0x12, 0x56, 0x41, 0x54, 0x56, 0x61, 0x6c, 0x69,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x46,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x46, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x46, 0x61, 0x75,
	0x6c, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x46, 0x61, 0x75, 0x6c, 0x74, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_vies_proto_rawDescOnce sync.Once
	file_vies_proto_rawDescData = file_vies_proto_rawDesc
)

func file_vies_proto_rawDescGZIP() []byte {
	file_vies_proto_rawDescOnce.Do(func() {
		file_vies_proto_rawDescData = protoimpl.X.CompressGZIP(file_vies_proto_rawDescData)
	})
	return file_vies_proto_rawDescData
}

var file_vies_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vies_proto_goTypes = []interface{}{
	(*VATValidationResponse)(nil),                    // 0: vies.VATValidationResponse
	(*VATValidationResponse_VATValidationError)(nil), // 1: vies.VATValidationResponse.VATValidationError
	(*timestamppb.Timestamp)(nil),                    // 2: google.protobuf.Timestamp
}
var file_vies_proto_depIdxs = []int32{
	2, // 0: vies.VATValidationResponse.RequestDate:type_name -> google.protobuf.Timestamp
	1, // 1: vies.VATValidationResponse.Error:type_name -> vies.VATValidationResponse.VATValidationError
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vies_proto_init() }
func file_vies_proto_init() {
	if File_vies_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vies_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VATValidationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vies_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VATValidationResponse_VATValidationError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vies_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vies_proto_goTypes,
		DependencyIndexes: file_vies_proto_depIdxs,
		MessageInfos:      file_vies_proto_msgTypes,
	}.Build()
	File_vies_proto = out.File
	file_vies_proto_rawDesc = nil
	file_vies_proto_goTypes = nil
	file_vies_proto_depIdxs = nil
}
